nelmio_api_doc:
    documentation:
        info:
            title: Balancer  
            description: The Balancer microservice is responsible for managing and distributing incoming requests to a pool of available working machines.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
