version: "3.9"
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: "balancer"
      POSTGRES_USER: "balancer"
      POSTGRES_PASSWORD: "balancer"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5477:5432"
    container_name: balancer_database
    restart: always