version: "3.9"
services:

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - APP_ENV=prod
    ports:
      - "9000:9000"
    depends_on:
      - database
    volumes:
      - ./:/var/www/app
    container_name: balancer_app

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www/app
    container_name: balancer_web

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: "balancer"
      POSTGRES_USER: "balancer"
      POSTGRES_PASSWORD: "balancer"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5477:5432"
    container_name: balancer_database
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: