# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entities/'
            - '../src/Kernel.php'

    App\ExceptionHandler:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }


    # Sevices

    App\Application\Services\ProcessService: ~
    App\Application\Services\MachineService: ~


    App\Application\Abstractions\Services\IProcessService: 
        class: 'App\Application\Services\RebalancedProcessesProcessService'
        arguments:
            $processService: '@App\Application\Services\ProcessService'

    App\Application\Abstractions\Services\IMachineService: 
        class: 'App\Application\Services\RebalancedProcessesMachineService'
        arguments:
            $machineService: '@App\Application\Services\MachineService'
    

    # Repositories

    App\Insfrastructure\Abstractions\Repositories\IProcessRepository: 
        class: 'App\Infrastructure\Repositories\ProcessRepository'

    App\Insfrastructure\Abstractions\Repositories\IMachineRepository:
        class: 'App\Infrastructure\Repositories\MachineRepository'

    # UseCases 

    App\Application\Abstractions\UseCases\IRebalanceProcessesUseCase:
        class: 'App\Application\UseCases\RebalanceProcessesUseCase'

    